#端口配置
server:
  port: 8002

#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.yxm.springcloud.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

#spring 配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimeZone=GMT%2B8
    username: root
    password: root

#eureka配置
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka/  #单机  将服务提供者服务注册到eureka的路径下
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #集群  将服务提供者服务注册到集群中
  instance:
    instance-id: springcloud-provider-dept8002   #修改eureka上的默认描述信息


#info配置  监控信息页面
info:
  app.name: yxm_springcloud
  company.name: www.yxm.com